name: places
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  rxdart: ^0.27.1
  provider: ^5.0.0
  svg_to_path_annotation: ^1.0.0
  flutter_bloc: ^7.0.1
  freezed_annotation: ^0.14.2
  shared_preferences: ^2.0.6
  moor: ^4.3.2
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.2
  path: ^1.8.0
  image_picker: ^0.8.0+3
  geolocator: ^7.2.0+1
  yandex_mapkit: ^1.0.1
  map_launcher: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  svg_to_path_generator: ^1.0.1+2
  freezed: ^0.14.2
  moor_generator: ^4.3.1

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: res/fonts/Roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: res/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: res/fonts/Roboto/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: res/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: res/fonts/Roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: res/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: res/fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
  assets:
    - res/
    - res/images/
