name: places
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  rxdart: ^0.27.0
  provider: ^5.0.0
  svg_to_path_annotation: ^1.0.0
  flutter_bloc: ^7.0.0
  freezed_annotation: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.3
  svg_to_path_generator: ^1.0.1+2
  freezed: ^0.14.2

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: res/fonts/Roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: res/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: res/fonts/Roboto/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: res/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: res/fonts/Roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: res/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: res/fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
  assets:
    - res/
    - res/images/
